
function aes_segeant_kill (stalker, player)
    local h = hit ()
    h.power = 100
    h.direction = vector():set (0, -1, 0)
    h.impulse = 1
    h.draftsman = stalker
    h.type = hit.strike
    player:hit (h)
    db.actor:give_info_portion ("aes_get_soldier_map")
end

function aes_set_mapspots (stalker, player)
    level_tasks.add_location (1102, "crlc_mdl", "aes_sarcofag_hint")
end

--' Мы отказываемся вступить в осознание, нас переносит на вторую станцию
function osoznanie_decline(npc, actor)
    db.actor:disable_info_portion("oso_init_dialog")
	npc:stop_talk()
    actor:stop_talk()
	xr_effects.enable_ui(db.actor, nil)	  
	local point = patrol("mon_jump_aes2_walk")
	local look = patrol("mon_jump_aes2_look")
	
	db.actor:set_actor_position(point:point(0))
	local dir = look:point(0):sub(point:point(0))
	db.actor:set_actor_direction(-dir:getH())
	
end

--' Мы соглашаемся вступить в осознание, конец игры.
function osoznanie_agree(npc, actor)
	db.actor:disable_info_portion("oso_init_dialog")
	npc:stop_talk()
    actor:stop_talk()
	xr_effects.enable_ui(db.actor, nil)	  
	game.start_tutorial("mov_join_osoznanie")
	
end