local ammo_data_table = {}
local updates_before_repack = nil
local actor = db.actor
local sim = alife()

local function repack_ammo(section, box_size)

	local release_table = {}
	local ammo_to_repack = 0
	local boxes_to_repack = 0

	for i = 0, actor:object_count() - 1 do
		local obj = actor:object(i)
		if obj:section() == section then
			local ammo_id = obj:id()
			local ammo_count = obj:get_ammo_count()
			if ammo_count ~= box_size then
				boxes_to_repack = boxes_to_repack + 1
				ammo_to_repack = ammo_to_repack + ammo_count
				release_table[ammo_id] = true
			end
		end
	end

	if boxes_to_repack > 1 or ammo_to_repack > box_size then

		for ammo_id in pairs (release_table) do
			sim:release(sim:object(ammo_id), true)
		end

		local vec = vector()

		while ammo_to_repack > box_size do
			ammo_to_repack = ammo_to_repack - box_size
			sim:create_ammo(section, vec, 0, 0, 0, box_size)
		end

		sim:create_ammo(section, vec, 0, 0, 0, ammo_to_repack)
	end
end

function on_update()
	if updates_before_repack then
		if updates_before_repack > 0 then
			updates_before_repack = updates_before_repack - 1
		else
			for section, ammo_data in pairs (ammo_data_table) do
				if ammo_data.need_repack then
					repack_ammo(section, ammo_data.box_size)
					ammo_data.need_repack = false
				end
			end
			updates_before_repack = nil
		end
	end
end

function on_take(ammo)

	local section = ammo:section()

	if section == nil then
		abort("[dunin_ammo.on_take]: No ammo section defined for '%s'.", ammo:name())
	end

	local ammo_data = ammo_data_table[section]

	if not ammo_data then
		ammo_data = {
			box_size = system_ini():r_u32(section, "box_size"),
			need_repack = false
		}
		ammo_data_table[section] = ammo_data
	end

	local box_size = ammo_data.box_size

	if box_size > 1 then
		if not ammo_data.need_repack then
			if box_size ~= ammo:get_ammo_count() then
				ammo_data.need_repack = true
				updates_before_repack = 150 -- hack per https://github.com/Decane/SRP/issues/150
			end
		end
	end
end