

local trade_manager = {
}





function trade_init(npc, cfg)
	--printf("TRADE INIT[%s]", npc:name())
	if trade_manager[npc:id()] == nil then
		trade_manager[npc:id()] = {}
	end

	trade_manager[npc:id()].cfg_ltx = cfg
	trade_manager[npc:id()].config = ini_file(cfg)
	
	-- коэфициенты покупки
	local str = utils.cfg_get_string(trade_manager[npc:id()].config, "trader", "buy_condition", npc, true, "")
	if str == nil then
		abort("Incorrect trader settings. Cannot find buy_condition. [%s]->[%s]", npc:name(), cfg)
	end
	trade_manager[npc:id()].buy_condition = xr_logic.parse_condlist(npc, "trade_manager", "buy_condition", str)
	
	-- коэфициенты продажи
	str = utils.cfg_get_string(trade_manager[npc:id()].config, "trader", "sell_condition", npc, true, "")
	if str == nil then
		abort("Incorrect trader settings. Cannot find sell_condition. [%s]->[%s]", npc:name(), cfg)
	end	
	trade_manager[npc:id()].sell_condition = xr_logic.parse_condlist(npc, "trade_manager", "sell_condition", str)
	
	-- список закупки
	str = utils.cfg_get_string(trade_manager[npc:id()].config, "trader", "buy_supplies", npc, false, "")
	if str ~= nil then
		trade_manager[npc:id()].buy_supplies = xr_logic.parse_condlist(npc, "trade_manager", "buy_supplies", str)
	end
end


function update(npc)
	local tt = trade_manager[npc:id()]
	
	if tt == nil then
		return
	end

	if tt.update_time ~= nil and game.get_game_time():diffSec(tt.update_time) < 3600 then
		return
	end
	tt.update_time = game.get_game_time()

	local str = xr_logic.pick_section_from_condlist(db.actor, npc, tt.buy_condition)
	if tt.current_buy_condition ~= str then
		--printf("TRADE [%s]: buy condition = %s", npc:name(), str)
		npc:buy_condition(tt.config, str)
		tt.current_buy_condition = str
	end

	str = xr_logic.pick_section_from_condlist(db.actor, npc, tt.sell_condition)
	if tt.current_sell_condition ~= str then
		--printf("TRADE [%s]: sell condition = %s", npc:name(), str)
		npc:sell_condition(tt.config, str)
		tt.current_sell_condition = str
	end

	if tt.buy_supplies == nil then
		return
	end

	str = xr_logic.pick_section_from_condlist(db.actor, npc, tt.buy_supplies)
	if tt.resupply_status == nil and tt.current_buy_supplies ~= str then
		tt.resupply_status = false
	end
	if tt.resupply_status == false or tt.resuply_time == nil or game.get_game_time():diffSec(tt.resuply_time) >= 86400 then
		--printf("TRADE [%s]: buy_supplies = %s", npc:name(), str)
		npc:buy_supplies(tt.config, str)
		tt.current_buy_supplies = str
		tt.resuply_time = game.get_game_time()
		if tt.resupply_status == false then
			tt.resupply_status = true
		else
			tt.resupply_status = nil
		end
	end
end


function save(obj, packet)
	local tt = trade_manager[obj:id()]

	--' Сохраняем присутствует ли инициализированная торговля в принципе.
	if tt == nil then
		--printf("TRADE SAVE [%s]: ignored", obj:name())
		packet:w_bool(false)
		return
	else
		packet:w_bool(true)
	end

	packet:w_stringZ(tt.cfg_ltx)

	--printf("TRADE SAVE [%s]: current_buy_condition = %s", obj:name(), tostring(tt.current_buy_condition))
	if tt.current_buy_condition == nil then
		packet:w_stringZ("")
	else
		packet:w_stringZ(tt.current_buy_condition)
	end

	--printf("TRADE SAVE [%s]: current_sell_condition = %s", obj:name(), tostring(tt.current_sell_condition))
	if tt.current_sell_condition == nil then
		packet:w_stringZ("")
	else
		packet:w_stringZ(tt.current_sell_condition)
	end

	--printf("TRADE SAVE [%s]: current_buy_supplies = %s", obj:name(), tostring(tt.current_buy_supplies))
	if tt.current_buy_supplies == nil then
		packet:w_stringZ("")
	else
		packet:w_stringZ(tt.current_buy_supplies)
	end

	if tt.update_time == nil then
		packet:w_u8(0)
	else
		packet:w_u8(1)
		utils.w_CTime(packet, tt.update_time)
	end

	if tt.resuply_time == nil then
		packet:w_u8(0)
	else
		packet:w_u8(1)
		utils.w_CTime(packet, tt.resuply_time)
	end

	if tt.resupply_status == nil then
		packet:w_u8(0)
	else
		packet:w_u8(1)
		packet:w_bool(tt.resupply_status)
	end
end

function load(obj, packet)
	local a = packet:r_bool()
	if a == false then
		--printf("TRADE LOAD [%s]: ignored", obj:name())
		return
	end

	trade_manager[obj:id()] = {}

	local tt = trade_manager[obj:id()]

	tt.cfg_ltx = packet:r_stringZ()
	--printf("TRADE LOAD [%s]: cfg_ltx = %s", obj:name(), tostring(tt.cfg_ltx))

	tt.config = ini_file(tt.cfg_ltx)

	a = packet:r_stringZ()
	--printf("TRADE LOAD [%s]: current_buy_condition = %s", obj:name(), tostring(a))
	if a ~= "" then
		tt.current_buy_condition = a
		obj:buy_condition(tt.config, a)
	end
	
	a = packet:r_stringZ()
	--printf("TRADE LOAD [%s]: current_sell_condition = %s", obj:name(), tostring(a))
	if a ~= "" then
		tt.current_sell_condition = a
		obj:sell_condition(tt.config, a)
	end

	a = packet:r_stringZ()
	--printf("TRADE LOAD [%s]: current_buy_supplies = %s", obj:name(), tostring(a))
	if a ~= "" then
		tt.current_buy_supplies = a	
	end

	a = packet:r_u8()
	if a == 1 then
		tt.update_time = utils.r_CTime(packet)
	end

	a = packet:r_u8()
	if a == 1 then
		tt.resuply_time = utils.r_CTime(packet)
	end

	a = packet:r_u8()
	if a == 1 then
		tt.resupply_status = packet:r_bool()
	end
end

function clear(npc_id)
	trade_manager[npc_id] = {}
end