class "opt_gameplay_adv" (CUIWindow)

function opt_gameplay_adv:__init() super()
end

function opt_gameplay_adv:__finalize()
end


function opt_gameplay_adv:InitControls(x, y, xml, handler)
	local ctl
	self:Init									(x,y, 738, 416)
	self:SetAutoDelete							(true)
	
	self.bk			= xml:InitFrame				("frame_gameplayadv", self)
	self.scroll_v	= xml:InitScrollView		("gameplay_adv:scroll_v", self)

	local _st		= xml:InitStatic			("gameplay_adv:templ_item",				self.scroll_v)
	handler:SetCapCallbacks						(_st, 									"descr_g_hit_mark_index")
	xml:InitStatic								("gameplay_adv:cap_g_hit_mark_index",			_st)
	xml:InitSpinNum								("gameplay_adv:spin_g_hit_mark_index",			_st)
--[[
	_st				= xml:InitStatic			("gameplay_adv:templ_item",				self.scroll_v)
	xml:InitStatic								("gameplay_adv:cap_g_use_ik",					_st)
	xml:InitCheck								("gameplay_adv:check_g_use_ik",					_st)
]]
	_st				= xml:InitStatic			("gameplay_adv:templ_item",				self.scroll_v)
	handler:SetCapCallbacks						(_st, 									"descr_g_use_lens")
	xml:InitStatic								("gameplay_adv:cap_g_use_lens",					_st)
	xml:InitCheck								("gameplay_adv:check_g_use_lens",				_st)

	_st				= xml:InitStatic			("gameplay_adv:templ_item",				self.scroll_v)
	handler:SetCapCallbacks						(_st, 									"descr_r2_bloom_mode")
	xml:InitStatic								("gameplay_adv:cap_r2_bloom_mode",				_st)
	xml:InitComboBox							("gameplay_adv:combo_r2_bloom_mode",			_st)

	_st				= xml:InitStatic			("gameplay_adv:templ_item",				self.scroll_v)
	handler:SetCapCallbacks						(_st, 									"descr_r2_indoor_lighting")
	xml:InitStatic								("gameplay_adv:cap_r2_indoor_lighting",			_st)
	xml:InitCheck								("gameplay_adv:check_r2_indoor_lighting",		_st)

	_st				= xml:InitStatic			("gameplay_adv:templ_item",				self.scroll_v)
	handler:SetCapCallbacks						(_st, 									"descr_r2_ls_bloom_fast")
	xml:InitStatic								("gameplay_adv:cap_r2_ls_bloom_fast",			_st)
	xml:InitCheck								("gameplay_adv:check_r2_ls_bloom_fast",			_st)

	_st				= xml:InitStatic			("gameplay_adv:templ_item",				self.scroll_v)
	handler:SetCapCallbacks						(_st, 									"descr_r2_mblur")
	xml:InitStatic								("gameplay_adv:cap_r2_mblur",					_st)
	xml:InitCheck								("gameplay_adv:check_r2_mblur",					_st)

	_st				= xml:InitStatic			("gameplay_adv:templ_item",				self.scroll_v)
	handler:SetCapCallbacks						(_st, 									"descr_r2_old_aref")
	xml:InitStatic								("gameplay_adv:cap_r2_old_aref",				_st)
	xml:InitCheck								("gameplay_adv:check_r2_old_aref",				_st)

	_st				= xml:InitStatic			("gameplay_adv:templ_item",				self.scroll_v)
	handler:SetCapCallbacks						(_st, 									"descr_r2_old_distort")
	xml:InitStatic								("gameplay_adv:cap_r2_old_distort",				_st)
	xml:InitCheck								("gameplay_adv:check_r2_old_distort",			_st)

	_st				= xml:InitStatic			("gameplay_adv:templ_item",				self.scroll_v)
	handler:SetCapCallbacks						(_st, 									"descr_r2_specular_rgb")
	xml:InitStatic								("gameplay_adv:cap_r2_specular_rgb",			_st)
	xml:InitCheck								("gameplay_adv:check_r2_specular_rgb",			_st)

	_st				= xml:InitStatic			("gameplay_adv:templ_item",				self.scroll_v)
	handler:SetCapCallbacks						(_st, 									"descr_r2_tonemap")
	xml:InitStatic								("gameplay_adv:cap_r2_tonemap",					_st)
	xml:InitCheck								("gameplay_adv:check_r2_tonemap",				_st)

	_st				= xml:InitStatic			("gameplay_adv:templ_item",				self.scroll_v)
	handler:SetCapCallbacks						(_st, 									"descr_r__smapsize")
	xml:InitStatic								("gameplay_adv:cap_r__smapsize",				_st)
	xml:InitComboBox							("gameplay_adv:combo_r__smapsize",				_st)

	_st				= xml:InitStatic			("gameplay_adv:templ_item",				self.scroll_v)
	handler:SetCapCallbacks						(_st, 									"descr_r__wallmarks_on_skeleton")
	xml:InitStatic								("gameplay_adv:cap_r__wallmarks_on_skeleton",	_st)
	xml:InitCheck								("gameplay_adv:check_r__wallmarks_on_skeleton",	_st)

	_st				= xml:InitStatic			("gameplay_adv:templ_item",				self.scroll_v)
	handler:SetCapCallbacks						(_st, 									"descr_weapon_bobbing")
	xml:InitStatic								("gameplay_adv:cap_weapon_bobbing",				_st)
	xml:InitCheck								("gameplay_adv:check_weapon_bobbing",			_st)

	btn		= xml:Init3tButton					("gameplay_adv:btn_to_simply",	self)	
	handler:Register							(btn, "btn_simply_gameplay")	
end
