local items_table = {
	                    {name = "spawn_all",	spawn = "all",	new_game = true},
						{name = "spawn_ds",		spawn = "ds"}
					}

class "spawn_item" (CUIListItemEx)

function spawn_item:__init() super()
	self:SetWndRect		(0,0,300,22)
	
	local ca = 255
	local cr = 216
	local cg = 186
	local cb = 140
	
	self.text					= CUIStatic	()
	self.text:SetAutoDelete		(true)
	self:AttachChild			(self.text)
	self.text:SetWndRect		(0,0,300,22)
	self.text:SetText			("filename")
	self.text:SetFont			(GetFontLetterica18Russian())
	self.text:SetTextColor		(ca,cr,cg,cb)
end


class "spawn_dialog" (CUIScriptWnd)

function spawn_dialog:__init() super()
   self:InitControls()
   self:InitCallBacks()
   self:FillList()
end

function spawn_dialog:__finalize()
end

function spawn_dialog:FillList()
	for i,v in ipairs(items_table) do
		self:AddItemToList(v.name)
	end
end

function spawn_dialog:InitControls()
	local xml				= CScriptXmlInit()
	local ctrl
	xml:ParseFile			("ui_spawn_dialog.xml")

	ctrl					= xml:InitStatic("background",self)
	

	self:SetWndPos			(100,100)
	self:SetWndSize			(ctrl:GetWidth(),ctrl:GetHeight())
	ctrl:SetWndPos			(0,0)

	self.list = xml:InitList	("list",self)
	self.list:ShowSelectedItem	(true)
	self:Register				(self.list, "list_window")
		
	ctrl						= xml:Init3tButton("btn_create",self)	
	self:Register				(ctrl, "btn_create")

	
	ctrl = xml:Init3tButton		("btn_close",self)	
	self:Register				(ctrl, "btn_close")
end

function spawn_dialog:InitCallBacks()
	self:AddCallback("btn_create",		ui_events.BUTTON_CLICKED,             self.OnButton_create_clicked,	self)
	self:AddCallback("btn_close",		ui_events.BUTTON_CLICKED,             self.OnButton_close_clicked,	self)
	self:AddCallback("list_window",		ui_events.WINDOW_LBUTTON_DB_CLICK,	  self.OnButton_create_clicked,	self)
end



function spawn_dialog:OnButton_create_clicked()	
	if self.list:GetSize()==0 then 
		return 
	end

	local index = self.list:GetSelectedItem()
	
	if index == -1 then 
		return 
	end

	local itm			= items_table[index+1]
	local itmname		= itm.spawn
	local console = get_console()
	console:execute("disconnect")
	console:execute("main_menu off")
	local need_new = itm.new_game or false
	if need_new then
		console:execute("start server(" .. itmname .. "/single/alife/new) client(localhost)")
	else
		console:execute("start server(" .. itmname .. "/single/alife/fast) client(localhost)")
	end
end

function spawn_dialog:OnButton_close_clicked()
--	self:GetHolder():start_stop_menu	(self.owner, true) --new
	self:GetHolder():start_stop_menu	(self,true)
	_G.si_dlg = nil
--	self.owner:Show						(true)
end

function spawn_dialog:OnKeyboard(dik, keyboard_action)
	local bind = dik_to_bind(dik)
	if bind == key_bindings.kQUIT then
		self:OnButton_close_clicked()
	else
	if dik==28 then
		self:OnButton_create_clicked()
	end
	end
	   
	return true
end

function spawn_dialog:AddItemToList(item_name)
	local _itm				= spawn_item()
	_itm.text:SetTextST		(item_name)
	
	self.list:AddItem		(_itm)
end



function main()
	if _G.si_dlg==nil then
		_G.si_dlg = spawn_dialog()
	end
	level.start_stop_menu(_G.si_dlg,true)
end
