;Русская версия шрифта small hud font. Этот шрифт
;использовался в ранних версиях игры, его можно
;увидеть в билде 2215 (англ. вер.)
;(c) 2008 Scavenger
;Не уверен, что в нём абсолютно всё правильно,
;но буквы и основные знаки в порядке.

[font_size]
height 	= 8
width	= 8
cpl	= 16
interval= 0.75
